OLED.init(64, 128)
RTC_DS1307.setTime(RTC_DS1307.TimeType.HOUR, 14)
RTC_DS1307.setTime(RTC_DS1307.TimeType.MINUTE, 15)
RTC_DS1307.setTime(RTC_DS1307.TimeType.SECOND, 0)
basic.forever(function () {
    OLED.clear()
    OLED.writeNum(0)
    OLED.writeString("")
    OLED.writeNum(0)
    OLED.newLine()
    OLED.writeString("Noise:")
    OLED.writeNum(Environment.ReadNoise(AnalogPin.P1))
    basic.pause(1000)
})
